### ISSUE TITLE
Key photo

### ISSUE THREAD

**Issue by nlessmann** [MIDL-Conference/midl-website-2020#1]
The 2018 and 2019 editions used a photograph of the city (Amsterdam/London) on the homepage and on the social media accounts. The 2020 bid book had a similar photo of Montreal as the background of the first page. Before this photo can be used in a similar way for the 2020 website, we need to verify who made this photo and under which license it is available to us. I couldn't find it back with a reverse Google image search.

**Comment by HKervadec** [comment]
Ismail bought the rights for this image:
![https://www.istockphoto.com/gb/photo/montreal-at-night-canada-gm495748747-41396754](https://media.istockphoto.com/photos/montreal-at-nightcanada-picture-id495748747)
https://www.istockphoto.com/gb/photo/montreal-at-night-canada-gm495748747-41396754

The [standard license](https://www.istockphoto.com/gb/help/licenses) seems sufficient for our use (as we do not resale posters or items using that image).

I will upload the original file (7110x4745px, 20MB) as well as a few already rescaled images in the asset folder I think.

**Comment by nlessmann** [comment]
Excellent!

Could you share the image via google drive or similar? If you upload it to this repository, it will automatically get published, so better only upload things that really are intended to go online.

**Comment by HKervadec** [comment]
> Could you share the image via google drive or similar?

Yes sure. Is there a preferred place to share that kind of assets yet ? (dedicated account, folder, ...) Otherwise I will simply post a sharing link here

**Comment by nlessmann** [comment]
There is a folder on Google drive, I've emailed you about that.
