### ISSUE TITLE
Inconsistent challenge proposal deadline

### ISSUE THREAD

**Issue by nlessmann** [MIDL-Conference/midl-website-2020#6]
Hi Hoel,

I changed a few details on the page on challenges to be in line with the design of the previous years. We noticed then that it helps a lot to use a big button for links to submission systems, otherwise many people somehow don't find it.

Anyway, I noticed that the page lists two different deadlines for submitting a challenge proposal: January 13 at the bottom in the list of important dates, and January 15 in the "Submission details" section.

**Comment by HKervadec** [comment]
Ah yes, thanks for those. So far I had only copied verbatim the call I was sent.

> Anyway, I noticed that the page lists two different deadlines for submitting a challenge proposal: January 13 at the bottom in the list of important dates, and January 15 in the "Submission details" section.

Nice catch. I'll enquire and fix this.

**Comment by HKervadec** [comment]
Fixed in f41b5c3
