### ISSUE TITLE
Inconsistency: short papers or extended abstracts?

### ISSUE THREAD

**Issue by nlessmann** [MIDL-Conference/midl-website-2020#7]
The "author instructions" mention extended abstracts while the call for papers mentions short papers.

**Comment by HKervadec** [comment]
Fixed in 898da02. I also updated the commented part (which still need to be validated by the program chairs).

**Comment by nlessmann** [comment]
👍 I think you also need to update the Latex template in this case, one of the templates also says "abstract"
